Repository SR-PLUM/SidheRigel, pull requests merged in 2023-12, with the labels that each got.

#161 Develop camera problem
  Config/DefaultEngine.ini
  Source/SidheRigel/SidheRigelCamera.cpp
  Source/SidheRigel/SidheRigelCamera.h
  Source/SidheRigel/SidheRigelCharacter.cpp
  Source/SidheRigel/SidheRigelGameMode.cpp
  Source/SidheRigel/SidheRigelGameMode.h
  Source/SidheRigel/SidheRigelPlayerController.cpp
  Source/SidheRigel/SidheRigelPlayerController.h
Labels: :lady_beetle: bug, feature

#162 Develop bulidings
  Source/SidheRigel/Character/FairyWing/FairyWingCharacter.cpp
  Source/SidheRigel/Nexus/Nexus.cpp
  Source/SidheRigel/Nexus/Nexus.h
  Source/SidheRigel/Tower/Tower.cpp
Labels: feature

#164 Develop server problem
  Content/Heros/Cold/BP_ColdCharacter.uasset
  Content/Heros/FairyWIng/BP_FairyWingCharacter.uasset
  Content/Heros/Kerun/BP_KerunCharacter.uasset
  Source/SidheRigel/Character/Cold/ColdAnimInstance.h
  Source/SidheRigel/Lobby/LobbyGameMode.cpp
  Source/SidheRigel/Lobby/LobbyPlayerController.h
  Source/SidheRigel/SidheRigelCharacter.cpp
  Source/SidheRigel/SidheRigelCharacter.h
  Source/SidheRigel/SidheRigelGameInstance.h
  Source/SidheRigel/SidheRigelPlayerController.cpp
  Source/SidheRigel/SidheRigelPlayerController.h
  Source/SidheRigel/State/AttackState.cpp
  Source/SidheRigel/State/AttackState.h
  Source/SidheRigel/State/AttackWaitState.cpp
  Source/SidheRigel/State/AttackWaitState.h
  Source/SidheRigel/State/DieState.cpp
  Source/SidheRigel/State/DieState.h
  Source/SidheRigel/State/IdleState.cpp
  Source/SidheRigel/State/IdleState.h
  Source/SidheRigel/State/MoveState.cpp
  Source/SidheRigel/State/MoveState.h
  Source/SidheRigel/State/MoveToAttackState.cpp
  Source/SidheRigel/State/MoveToAttackState.h
  Source/SidheRigel/State/State.cpp
  Source/SidheRigel/State/State.h
  Source/SidheRigel/State/StateMachine.cpp
  Source/SidheRigel/State/StateMachine.h
  Source/SidheRigel/State/StunState.cpp
  Source/SidheRigel/State/StunState.h
  Source/SidheRigel/State/UseSkillState.cpp
  Source/SidheRigel/State/UseSkillState.h
Labels: :lady_beetle: bug

#165 [Update] Increase CameraMoveAmount
  Source/SidheRigel/SidheRigelCamera.cpp
  Source/SidheRigel/SidheRigelCamera.h
Labels: feature

#166 [Update] InActiveCharacterIcon
  Content/UIBlueprints/WBP_LobbyMenu.uasset
  Source/SidheRigel/Lobby/LobbyMenu.cpp
Labels: feature

#167 [Update] move Create InGameUI to Character
  Source/SidheRigel/Character/Kerun/KerunCharacter.cpp
  Source/SidheRigel/InGameMapScriptActor.cpp
  Source/SidheRigel/SidheRigelCharacter.cpp
  Source/SidheRigel/SidheRigelCharacter.h
Labels: :lady_beetle: bug, feature, Refactor

#168 Develop state machine
  Content/Heros/AI/ABP_KerunAnimCharacter.uasset
  Content/Heros/AI/BP_AICharacterSpawner.uasset
  Content/Heros/AI/BP_AISidheRigelCharacter.uasset
  Content/__ExternalActors__/Maps/TrainingRoom/6/RW/DM43IL9RKW2YMN5QWDXHFZ.uasset
  Source/SidheRigel/Character/AI/AICharacterSpawner.cpp
  Source/SidheRigel/Character/AI/AICharacterSpawner.h
  Source/SidheRigel/Character/AI/AISidheRigelCharacter.cpp
  Source/SidheRigel/Character/AI/AISidheRigelCharacter.h
  Source/SidheRigel/Character/AI/CharacterAIController.cpp
  Source/SidheRigel/Character/AI/CharacterAIController.h
  Source/SidheRigel/Character/Cold/ColdAnimInstance.cpp
  Source/SidheRigel/Character/Cold/ColdAnimInstance.h
  Source/SidheRigel/Character/Kerun/KerunCharacter.cpp
  Source/SidheRigel/Minion/MinionAIController.h
  Source/SidheRigel/SidheRigelCharacter.cpp
  Source/SidheRigel/SidheRigelCharacter.h
  Source/SidheRigel/SidheRigelPlayerController.cpp
  Source/SidheRigel/SidheRigelPlayerController.h
  Source/SidheRigel/State/AttackState.cpp
  Source/SidheRigel/State/AttackWaitState.cpp
  Source/SidheRigel/State/DieState.cpp
  Source/SidheRigel/State/IdleState.cpp
  Source/SidheRigel/State/MoveState.cpp
  Source/SidheRigel/State/MoveToAttackState.cpp
  Source/SidheRigel/State/State.cpp
  Source/SidheRigel/State/State.h
  Source/SidheRigel/State/StateMachine.cpp
  Source/SidheRigel/State/StateMachine.h
  Source/SidheRigel/State/StunState.cpp
  Source/SidheRigel/State/UseSkillState.cpp
Labels: Refactor

#169 [Update] Change Stun Mechanism
  Source/SidheRigel/SidheRigelCharacter.cpp
  Source/SidheRigel/SidheRigelPlayerController.h
  Source/SidheRigel/State/AttackWaitState.cpp
Labels: Refactor

#170 [Fix] StateMachine Update Error
  Source/SidheRigel/SidheRigelPlayerController.cpp
  Source/SidheRigel/SidheRigelPlayerController.h
Labels: :lady_beetle: bug

#171 Develop loading screen
  Content/UIBlueprints/WBP_LoadingScreen.uasset
  Content/UIBlueprints/WBP_LobbyMenu.uasset
  Source/SidheRigel/Lobby/LoadingScreen.cpp
  Source/SidheRigel/Lobby/LoadingScreen.h
  Source/SidheRigel/Lobby/LobbyGameMode.cpp
  Source/SidheRigel/Lobby/LobbyGameMode.h
  Source/SidheRigel/Lobby/LobbyMenu.cpp
  Source/SidheRigel/Lobby/LobbyMenu.h
Labels: feature

#176 [Update] Add Minion Projectile Static Mesh
  Content/Minion/BP_MinionProjectile.uasset
  Content/Minion/P_MinionProjectile.uasset
  Content/Minion/SM_MinionProjectile.uasset
  Source/SidheRigel/Minion/MinionProjectile.cpp
Labels: feature

#177 Develop menu design
  Content/Megascans/Images/loadingscreen_image.uasset
  Content/Megascans/Images/lobby_image.uasset
  Content/Megascans/Images/lobby_image_2.uasset
  Content/Megascans/Images/mainmenu_image.uasset
  Content/Megascans/Images/mainmenu_image_2.uasset
  Content/Megascans/Images/mainmenu_image_3.uasset
  Content/Megascans/Images/quitbutton_image.uasset
  Content/UIBlueprints/WBP_LobbyMenu.uasset
  Content/UIBlueprints/WBP_Mainmenu.uasset
Labels: feature

#179 Develop ai
  Content/Heros/AI/ABP_KerunAIAnimCharacter.uasset
  Content/Heros/AI/ABP_KerunAnimCharacter.uasset
  Content/Heros/AI/BP_AICharacterSpawner.uasset
  Content/Heros/AI/BP_AISidheRigelCharacter.uasset
  Content/__ExternalActors__/Maps/TrainingRoom/0/SE/P04K7VRCLQVG1J5K0WEQTM.uasset
  Content/__ExternalActors__/Maps/TrainingRoom/2/N3/I923VRLHN6VQI6XDVX0SAH.uasset
  Content/__ExternalActors__/Maps/TrainingRoom/7/Y0/UCIVXGXRFM816CMMLM6YKS.uasset
  Content/__ExternalActors__/Maps/TrainingRoom/A/90/XQFN3XER1XMAMT792EC4QI.uasset
  Content/__ExternalActors__/Maps/TrainingRoom/A/QQ/O8EUY5C7B2CDKUUCVTCPPW.uasset
  Content/__ExternalActors__/Maps/TrainingRoom/B/Q5/JPO7HY45WVWN11MWY6KDJH.uasset
  Content/__ExternalActors__/Maps/TrainingRoom/C/X6/439DNIF9DSZY6L5A28D5BV.uasset
  Content/__ExternalActors__/Maps/TrainingRoom/E/U4/LBPLZG08MTD1KRJMILN4EI.uasset
  Content/__ExternalActors__/Maps/TrainingRoom/F/03/W24KXTK7N9JN7VI2IUNPS4.uasset
  Content/__ExternalActors__/Maps/TrainingRoom/F/4I/5SEHN0VLCKS9PNXMUEE5WX.uasset
  Source/SidheRigel/Character/AI/AICharacterSpawner.cpp
  Source/SidheRigel/Character/AI/AICharacterSpawner.h
  Source/SidheRigel/Character/AI/AISidheRigelCharacter.cpp
  Source/SidheRigel/Character/AI/AISidheRigelCharacter.h
  Source/SidheRigel/Character/AI/CharacterAIController.cpp
  Source/SidheRigel/Character/AI/CharacterAIController.h
  Source/SidheRigel/Character/Kerun/KerunCharacter.cpp
  Source/SidheRigel/Lobby/LobbyGameMode.h
  Source/SidheRigel/Minion/Minion.cpp
  Source/SidheRigel/Minion/WayPoint.h
  Source/SidheRigel/SidheRigelCharacter.cpp
  Source/SidheRigel/SidheRigelCharacter.h
  Source/SidheRigel/SidheRigelPlayerController.cpp
  Source/SidheRigel/SidheRigelPlayerController.h
Labels: :lady_beetle: bug, feature, Refactor

#180 [Update] Change Enemy HP Color
  Source/SidheRigel/Minion/Minion.cpp
  Source/SidheRigel/Nexus/Nexus.cpp
  Source/SidheRigel/Tower/Tower.cpp
Labels: feature

#181 Develop ai
  Content/Heros/AI/BP_AISidheRigelCharacter.uasset
  Source/SidheRigel/Character/AI/AISidheRigelCharacter.cpp
  Source/SidheRigel/Character/AI/AISidheRigelCharacter.h
  Source/SidheRigel/Character/Kerun/KerunCharacter.h
  Source/SidheRigel/Character/Kerun/Skills/KerunWSkill.cpp
  Source/SidheRigel/Character/Skill.cpp
  Source/SidheRigel/SidheRigelCharacter.cpp
  Source/SidheRigel/SidheRigelCharacter.h
Labels: feature

#182 [Fix] minion, tower Target
  Source/SidheRigel/Minion/Minion.cpp
  Source/SidheRigel/Tower/Tower.cpp
Labels: :lady_beetle: bug

#183 [Fix] None Character Error
  Source/SidheRigel/Lobby/LobbyMenu.cpp
  Source/SidheRigel/Lobby/LobbyPlayerController.cpp
  Source/SidheRigel/Lobby/LobbyPlayerController.h
Labels: :lady_beetle: bug

#185 [Update] FairyWing Balancing, FairyWing Use Mana, Add Mana Progress B…
  Content/UIBlueprints/InGameUI/WBP_StatSummary.uasset
  Source/SidheRigel/Character/FairyWing/FairyWingCharacter.cpp
  Source/SidheRigel/Character/FairyWing/Skill/FairyWingESkill.cpp
  Source/SidheRigel/Character/FairyWing/Skill/FairyWingQSkill.cpp
  Source/SidheRigel/Character/FairyWing/Skill/FairyWingRSkill.cpp
  Source/SidheRigel/Character/FairyWing/Skill/FairyWingWSkill.cpp
  Source/SidheRigel/SidheRigelCharacter.cpp
  Source/SidheRigel/SidheRigelCharacter.h
  Source/SidheRigel/UI/StatSummary.cpp
  Source/SidheRigel/UI/StatSummary.h
Labels: feature

#186 [Fix] FairyWing R Skill Bug
  Source/SidheRigel/Character/FairyWing/Skill/FairyWingRCollider.cpp
Labels: :lady_beetle: bug

#188 [Update] Can Toggle Setting UI
  Content/Maps/TrainingRoom.umap
  Source/SidheRigel/SidheRigelGameInstance.cpp
  Source/SidheRigel/SidheRigelGameInstance.h
Labels: feature

#189 [Fix] ProjectileRemain Bug
  Source/SidheRigel/Dummy/DummyProjectile.cpp
Labels: :lady_beetle: bug

#190 Develop camera toggle feature
  Config/DefaultInput.ini
  Source/SidheRigel/SidheRigelCamera.cpp
  Source/SidheRigel/SidheRigelPlayerController.cpp
  Source/SidheRigel/SidheRigelPlayerController.h
Labels: feature

#191 Develop delay minion spawn
  Source/SidheRigel/Minion/MinionSpawner.cpp
  Source/SidheRigel/Minion/MinionSpawner.h
Labels: :lady_beetle: bug, feature

#192 Develop fix UI anchor
  Content/UIBlueprints/WBP_LoadingScreen.uasset
  Content/UIBlueprints/WBP_LobbyMenu.uasset
  Content/UIBlueprints/WBP_Mainmenu.uasset
Labels: :lady_beetle: bug, feature

#195 [Update] Add Attack Sound
  Content/Heros/Cold/BP_ColdAttackProjectile.uasset
  Content/Heros/Cold/Sounds/SW_Cold_Attack_HitSound.uasset
  Content/Heros/Cold/Sounds/SW_Cold_Attack_SpawnSound.uasset
  Content/Heros/FairyWIng/BP_FairyWingAttackProjectile.uasset
  Content/Heros/FairyWIng/Sounds/SW_FairyWing_Attack_HitSound.uasset
  Content/Heros/FairyWIng/Sounds/SW_FairyWing_Attack_SpawnSound.uasset
  Content/Heros/Kerun/BP_KerunAttackProjectile.uasset
  Content/Heros/Kerun/Sounds/SW_Kerun_Attack_HitSound.uasset
  Content/Heros/Kerun/Sounds/SW_Kerun_Attack_SpawnSound.uasset
  Source/SidheRigel/Character/Kerun/KerunAttackProjectile.cpp
  Source/SidheRigel/Dummy/DummyProjectile.cpp
  Source/SidheRigel/Dummy/DummyProjectile.h
Labels: feature

#194 Develop outline
  Config/DefaultEngine.ini
  Content/Heros/AI/BP_AISidheRigelCharacter.uasset
  Content/Heros/Cold/BP_ColdCharacter.uasset
  Content/Heros/FairyWIng/BP_FairyWingCharacter.uasset
  Content/Heros/Kerun/BP_KerunCharacter.uasset
  Content/Landscape/M_Highlight.uasset
  Content/Maps/TrainingRoom.umap
  Content/Minion/BP_Minion.uasset
  Content/Minion/BP_RangeMinion.uasset
  Content/Nexus/BP_Nexus.uasset
  Content/Tower/BP_Tower.uasset
  Content/__ExternalActors__/Maps/TrainingRoom/0/CV/38SKD4S8ENWELQUIUHRAAE.uasset
Labels: feature

#196 [Add] Attack Use A Button
  Config/DefaultInput.ini
  Source/SidheRigel/SidheRigelCharacter.cpp
  Source/SidheRigel/SidheRigelPlayerController.cpp
  Source/SidheRigel/SidheRigelPlayerController.h
  Source/SidheRigel/State/AttackState.cpp
  Source/SidheRigel/State/AttackWaitState.cpp
  Source/SidheRigel/State/IdleState.cpp
  Source/SidheRigel/State/MoveState.cpp
  Source/SidheRigel/State/MoveToAttackState.cpp
Labels: feature

#197 [Add] AI Dead State
  Source/SidheRigel/Character/AI/AISidheRigelCharacter.cpp
  Source/SidheRigel/Character/AI/AISidheRigelCharacter.h
Labels: feature

#198 [Fix] AI Animation
  Content/Heros/AI/Anim_KerunAIAttackMontage.uasset
  Content/Heros/AI/Anim_KerunAIRSkillMontage.uasset
  Content/Heros/AI/Anim_KerunAIWSkillEnd.uasset
  Content/Heros/AI/Anim_KerunAIWSkillStart.uasset
  Content/Heros/AI/BP_AISidheRigelCharacter.uasset
  Content/Heros/AI/BP_KerunAIDeathActor.uasset
  Source/SidheRigel/Character/AI/AISidheRigelCharacter.cpp
Labels: :lady_beetle: bug

#199 Develop character balancing
  Source/SidheRigel/Character/AI/AISidheRigelCharacter.cpp
  Source/SidheRigel/Character/Cold/ColdCharacter.cpp
  Source/SidheRigel/Character/Cold/ColdCharacter.h
  Source/SidheRigel/Character/Cold/Skill/ColdESkill.cpp
  Source/SidheRigel/Character/Cold/Skill/ColdESkill.h
  Source/SidheRigel/Character/Cold/Skill/ColdQSkill.cpp
  Source/SidheRigel/Character/Cold/Skill/ColdQSkill.h
  Source/SidheRigel/Character/Cold/Skill/ColdR2Skill.cpp
  Source/SidheRigel/Character/Cold/Skill/ColdR2Skill.h
  Source/SidheRigel/Character/Cold/Skill/ColdWSkill.cpp
  Source/SidheRigel/Character/Cold/Skill/ColdWSkill.h
  Source/SidheRigel/Character/FairyWing/FairyWingCharacter.cpp
  Source/SidheRigel/Character/FairyWing/FairyWingCharacter.h
  Source/SidheRigel/Character/FairyWing/Skill/FairyWingQCollider.cpp
  Source/SidheRigel/Character/FairyWing/Skill/FairyWingWCollider.cpp
  Source/SidheRigel/Character/Kerun/KerunCharacter.cpp
  Source/SidheRigel/Character/Kerun/KerunCharacter.h
  Source/SidheRigel/Character/Kerun/Skills/KerunQSkill.cpp
  Source/SidheRigel/Character/Kerun/Skills/KerunR1Skill.cpp
  Source/SidheRigel/Character/Kerun/Skills/KerunWSkill.cpp
  Source/SidheRigel/Character/Kerun/Skills/KerunWSkill.h
  Source/SidheRigel/Minion/Minion.cpp
  Source/SidheRigel/Minion/RangeMinion.cpp
  Source/SidheRigel/SidheRigelCharacter.cpp
  Source/SidheRigel/SidheRigelCharacter.h
  Source/SidheRigel/Tower/Tower.h
Labels: feature

#200 [Fix] Can Use Ult When Level 10
  Source/SidheRigel/Character/Skill.cpp
Labels: :lady_beetle: bug

#201 [Fix] Cant Attack Nexus Before Destroy Tower
  Content/__ExternalActors__/Maps/TrainingRoom/3/Y4/90Y0BGDT4XWOKUQ3Q1WHLQ.uasset
  Content/__ExternalActors__/Maps/TrainingRoom/B/48/7K50U1MMY3P1IRIAX2IXXS.uasset
  Source/SidheRigel/Nexus/Nexus.h
  Source/SidheRigel/SidheRigelPlayerController.cpp
  Source/SidheRigel/Tower/Tower.cpp
  Source/SidheRigel/Tower/Tower.h
Labels: :lady_beetle: bug

#203 Develop victory screen
  Content/UIBlueprints/InGameUI/WBP_GameOverUI.uasset
  Content/UIBlueprints/InGameUI/WBP_InGameUI.uasset
  Content/UIBlueprints/InGameUI/defeatImage.uasset
  Content/UIBlueprints/InGameUI/victoryImage.uasset
  Source/SidheRigel/Nexus/Nexus.cpp
  Source/SidheRigel/SidheRigelCharacter.cpp
  Source/SidheRigel/SidheRigelCharacter.h
  Source/SidheRigel/SidheRigelGameMode.cpp
  Source/SidheRigel/SidheRigelGameMode.h
  Source/SidheRigel/SidheRigelPlayerController.cpp
  Source/SidheRigel/SidheRigelPlayerController.h
  Source/SidheRigel/State/UseSkillState.h
  Source/SidheRigel/UI/GameOverUI.cpp
  Source/SidheRigel/UI/GameOverUI.h
  Source/SidheRigel/UI/InGameUI.h
Labels: feature

#202 [Fix] Cant Move Continuous When Using Skill With Move
  Source/SidheRigel/SidheRigelPlayerController.cpp
Labels: :lady_beetle: bug

#204 Develop kerun projectile
  Content/Heros/Kerun/BP_KerunAttackProjectile.uasset
  Source/SidheRigel/Character/Kerun/KerunAnimInstance.cpp
  Source/SidheRigel/Character/Kerun/KerunCharacter.cpp
  Source/SidheRigel/Character/Kerun/Skills/KerunQSkill.cpp
Labels: :lady_beetle: bug

#205 Develop fairy wing
  Source/SidheRigel/Character/FairyWing/FairyWingCharacter.cpp
  Source/SidheRigel/Character/FairyWing/Skill/FairyWingESkill.cpp
  Source/SidheRigel/Character/FairyWing/Skill/FairyWingQCollider.cpp
  Source/SidheRigel/Character/FairyWing/Skill/FairyWingQCollider.h
  Source/SidheRigel/Character/FairyWing/Skill/FairyWingQSkill.cpp
  Source/SidheRigel/Character/FairyWing/Skill/FairyWingQSkill.h
  Source/SidheRigel/Character/FairyWing/Skill/FairyWingRCollider.cpp
  Source/SidheRigel/Character/FairyWing/Skill/FairyWingRCollider.h
  Source/SidheRigel/Character/FairyWing/Skill/FairyWingRSkill.cpp
  Source/SidheRigel/Character/FairyWing/Skill/FairyWingRSkill.h
  Source/SidheRigel/Character/FairyWing/Skill/FairyWingWCollider.cpp
  Source/SidheRigel/Character/FairyWing/Skill/FairyWingWCollider.h
  Source/SidheRigel/Character/FairyWing/Skill/FairyWingWSkill.cpp
Labels: feature

#207 Develop character balancing
  Source/SidheRigel/Character/FairyWing/Skill/FairyWingESkill.cpp
  Source/SidheRigel/Character/FairyWing/Skill/FairyWingESkill.h
  Source/SidheRigel/Character/FairyWing/Skill/FairyWingQSkill.h
  Source/SidheRigel/Character/FairyWing/Skill/FairyWingWSkill.h
Labels: feature

#206 [Update] AI Movement Improvement
  Content/Heros/AI/BP_KerunAIDeathActor.uasset
  Source/SidheRigel/Character/AI/AISidheRigelCharacter.cpp
  Source/SidheRigel/Character/AI/AISidheRigelCharacter.h
  Source/SidheRigel/Character/Cold/Skill/ColdEDamageField.cpp
  Source/SidheRigel/Character/Cold/Skill/ColdEDamageField.h
  Source/SidheRigel/Character/Cold/Skill/ColdESkill.cpp
  Source/SidheRigel/Character/Cold/Skill/ColdESkill.h
  Source/SidheRigel/SidheRigelCharacter.cpp
  Source/SidheRigel/State/IdleState.cpp
  Source/SidheRigel/Tower/Tower.cpp
  Source/SidheRigel/Tower/Tower.h
Labels: :lady_beetle: bug, feature

#209 [Fix] AI Attack Nexus
  Source/SidheRigel/Character/AI/AISidheRigelCharacter.cpp
Labels: :lady_beetle: bug

#210 [Fix] Add Range When Attack Nexus
  Source/SidheRigel/Minion/Minion.cpp
  Source/SidheRigel/SidheRigelCharacter.cpp
Labels: :lady_beetle: bug

#208 [Fix] Mana Restore When dead
  Source/SidheRigel/SidheRigelCharacter.cpp
  Source/SidheRigel/SidheRigelCharacter.h
  Source/SidheRigel/State/DieState.cpp
Labels: :lady_beetle: bug

#211 [Fix] Set Visibility False WayPoint
  Content/Minion/BP_WayPoint.uasset
Labels: :lady_beetle: bug

#212 [Fix] Nexus Nav Mesh, Minion Range
  Content/Nexus/SM_Nexus.uasset
  Source/SidheRigel/Minion/Minion.cpp
Labels: :lady_beetle: bug

#213 [Fix] Kerun Balancing, Bug Fix
  Source/SidheRigel/Character/Kerun/KerunCharacter.cpp
  Source/SidheRigel/Character/Kerun/KerunCharacter.h
  Source/SidheRigel/Character/Kerun/Skills/KerunQSkill.cpp
  Source/SidheRigel/Dummy/DummyProjectile.cpp
  Source/SidheRigel/SidheRigelCharacter.cpp
  Source/SidheRigel/SidheRigelCharacter.h
  Source/SidheRigel/Tower/Tower.cpp
Labels: :lady_beetle: bug, feature

#216 [Fix] Character Detect Late
  Content/Heros/AI/BP_AISidheRigelCharacter.uasset
  Content/Heros/Cold/BP_ColdCharacter.uasset
  Content/Heros/FairyWIng/BP_FairyWingCharacter.uasset
  Content/Heros/Kerun/BP_KerunCharacter.uasset
  Content/TopDown/Blueprints/BP_TopDownCharacter.uasset
  Source/SidheRigel/Character/AI/AISidheRigelCharacter.cpp
  Source/SidheRigel/Minion/Minion.cpp
  Source/SidheRigel/Minion/Minion.h
  Source/SidheRigel/Nexus/Nexus.cpp
  Source/SidheRigel/Nexus/Nexus.h
  Source/SidheRigel/Tower/Tower.cpp
  Source/SidheRigel/Tower/Tower.h
Labels: :lady_beetle: bug

#217 Develop remove combat summary
  Source/SidheRigel/Character/AI/AISidheRigelCharacter.cpp
  Source/SidheRigel/Character/AI/CharacterAIController.h
  Source/SidheRigel/UI/InGameUI.cpp
Labels: :lady_beetle: bug, feature

#218 Develop fix nexus range bug
  Source/SidheRigel/Character/AI/AISidheRigelCharacter.cpp
  Source/SidheRigel/Nexus/Nexus.cpp
  Source/SidheRigel/Nexus/Nexus.h
  Source/SidheRigel/Tower/Tower.cpp
Labels: :lady_beetle: bug
