Repository SR-PLUM/SidheRigel, pull requests merged in 2023-10, with the labels that each got.

#69 Develop cc
  Source/SidheRigel/Character/ACM/Skills/ACMECollider.cpp
  Source/SidheRigel/Character/FairyWing/Skill/FairyWingWCollider.cpp
  Source/SidheRigel/Dummy/Dummy.cpp
  Source/SidheRigel/Dummy/Dummy.h
  Source/SidheRigel/Interface/CCable.h
  Source/SidheRigel/SidheRigelCharacter.cpp
  Source/SidheRigel/SidheRigelCharacter.h
  Source/SidheRigel/State/AttackState.cpp
  Source/SidheRigel/State/StateMachine.cpp
  Source/SidheRigel/State/StateMachine.h
  Source/SidheRigel/State/StopState.cpp
  Source/SidheRigel/State/StopState.h
  Source/SidheRigel/State/StunState.cpp
Labels: feature

#74 Develop black wizard
  Source/SidheRigel/Character/BlackWizard/BlackWizardCharacter.cpp
  Source/SidheRigel/Character/BlackWizard/BlackWizardCharacter.h
  Source/SidheRigel/Character/BlackWizard/Skill/BlackWizardECollider.cpp
  Source/SidheRigel/Character/BlackWizard/Skill/BlackWizardECollider.h
  Source/SidheRigel/Character/BlackWizard/Skill/BlackWizardESkill.cpp
  Source/SidheRigel/Character/BlackWizard/Skill/BlackWizardESkill.h
  Source/SidheRigel/Character/BlackWizard/Skill/BlackWizardQCollider.cpp
  Source/SidheRigel/Character/BlackWizard/Skill/BlackWizardQCollider.h
  Source/SidheRigel/Character/BlackWizard/Skill/BlackWizardQSkill.cpp
  Source/SidheRigel/Character/BlackWizard/Skill/BlackWizardQSkill.h
  Source/SidheRigel/Character/BlackWizard/Skill/BlackWizardRCollider.cpp
  Source/SidheRigel/Character/BlackWizard/Skill/BlackWizardRCollider.h
  Source/SidheRigel/Character/BlackWizard/Skill/BlackWizardRSkill.cpp
  Source/SidheRigel/Character/BlackWizard/Skill/BlackWizardRSkill.h
Labels: feature

#75 [Add] Add Tower
  Content/Maps/TrainingRoom.umap
  Content/Tower/BP_Tower.uasset
  Content/Tower/MaterialSphere.uasset
  Content/__ExternalActors__/Maps/TrainingRoom/3/3Z/U8P8JLKQD0LN45FZZ5T4UO.uasset
  Content/__ExternalActors__/Maps/TrainingRoom/5/S5/2761LGC9YKTDW15W6YR7UY.uasset
  Content/__ExternalActors__/Maps/TrainingRoom/7/Y0/UCIVXGXRFM816CMMLM6YKS.uasset
  Content/__ExternalActors__/Maps/TrainingRoom/A/QQ/O8EUY5C7B2CDKUUCVTCPPW.uasset
  Content/__ExternalActors__/Maps/TrainingRoom/C/X6/439DNIF9DSZY6L5A28D5BV.uasset
  Content/__ExternalActors__/Maps/TrainingRoom/D/3E/QOVM6SP3YMJRLOGR00C0GU.uasset
  Content/__ExternalActors__/Maps/TrainingRoom/F/4I/5SEHN0VLCKS9PNXMUEE5WX.uasset
  Source/SidheRigel/Lobby/LobbyMenu.cpp
  Source/SidheRigel/Minion/Minion.cpp
  Source/SidheRigel/Tower/Tower.cpp
  Source/SidheRigel/Tower/Tower.h
Labels: feature

#78 [Fix] Skill Cooldown Error
  Source/SidheRigel/State/StateMachine.cpp
Labels: :lady_beetle: bug

#79 [Fix] Cold Skill Error
  Content/Heros/Cold/BP_ColdCharacter.uasset
  Source/SidheRigel/Character/Cold/ColdCharacter.cpp
  Source/SidheRigel/Character/Cold/ColdCharacter.h
  Source/SidheRigel/Character/Cold/Skill/ColdQProjectile.cpp
  Source/SidheRigel/Character/Cold/Skill/ColdQSkill.cpp
  Source/SidheRigel/Character/Cold/Skill/ColdQSkill.h
  Source/SidheRigel/State/UseSkillState.cpp
Labels: :lady_beetle: bug

#80 [Update] Tower Asset, Can Edit Team in Editor
  Content/Tower/BP_Tower.uasset
  Content/Tower/S_Modular_Gate_Pillars_xfxoeigiy_lod0_Var1.uasset
  Content/__ExternalActors__/Maps/TrainingRoom/6/8Z/46655D33N7LW1FZMY2HF4H.uasset
  Content/__ExternalActors__/Maps/TrainingRoom/D/3E/QOVM6SP3YMJRLOGR00C0GU.uasset
  Source/SidheRigel/Minion/Minion.h
  Source/SidheRigel/Tower/Tower.h
Labels: feature

#84 Develop can use skill
  Source/SidheRigel/Character/Skill.cpp
  Source/SidheRigel/Character/Skill.h
  Source/SidheRigel/State/AttackState.cpp
  Source/SidheRigel/State/AttackWaitState.cpp
  Source/SidheRigel/State/IdleState.cpp
  Source/SidheRigel/State/MoveState.cpp
  Source/SidheRigel/State/MoveToAttackState.cpp
  Source/SidheRigel/State/StateMachine.cpp
Labels: :lady_beetle: bug

#85 Develop team attack error
  Source/SidheRigel/State/StateMachine.cpp
Labels: :lady_beetle: bug

#86 [Fix] When Attack Enemy Character, Tower And Minion Attack AttackCharacter
  Source/SidheRigel/SidheRigelCharacter.cpp
  Source/SidheRigel/SidheRigelCharacter.h
Labels: :lady_beetle: bug

#87 [Fix] Move Minion Whne Delete Target
  Source/SidheRigel/Minion/Minion.cpp
Labels: :lady_beetle: bug

#90 Develop minion spawner
  Content/Minion/BP_MinionSpawner.uasset
  Content/__ExternalActors__/Maps/TrainingRoom/2/9E/ZI5P8YZ5Q13UK9K9JO9L9X.uasset
  Content/__ExternalActors__/Maps/TrainingRoom/3/3Z/U8P8JLKQD0LN45FZZ5T4UO.uasset
  Content/__ExternalActors__/Maps/TrainingRoom/8/BX/KK0PKLSBCS50IVJIYZKNHT.uasset
  Source/SidheRigel/Character/Cold/ColdCharacter.cpp
  Source/SidheRigel/Minion/Minion.cpp
  Source/SidheRigel/Minion/Minion.h
  Source/SidheRigel/Minion/MinionAIController.cpp
  Source/SidheRigel/Minion/MinionSpawner.cpp
  Source/SidheRigel/Minion/MinionSpawner.h
Labels: feature

#92 [Fix] add UpdateMoney function
  Source/SidheRigel/SidheRigelCharacter.cpp
Labels: :lady_beetle: bug

#93 Develop fog of war
  Config/DefaultEngine.ini
  Content/FogOfWar/FogOfWar.uasset
  Content/FogOfWar/FogOfWarMaterial.uasset
  Content/FogOfWar/FogOfWarRender.uasset
  Content/FogOfWar/FogOfWarRevealMaterial.uasset
  Content/FogOfWar/FogOfWarRevealRender.uasset
  Content/Heros/BlackWizard/BP_BlackWizardCharacter.uasset
  Content/__ExternalActors__/Maps/TrainingRoom/9/TV/Y36JDFMCGQAUO2RSRMACN8.uasset
Labels: feature

#95 [Add] Minion Attack Projectile
  Content/Minion/BP_MinionProjectile.uasset
  Content/Tower/BP_TowerAttackProjectile.uasset
  Source/SidheRigel/Character/ACM/ACMAttackProjectile.cpp
  Source/SidheRigel/Character/BlackWizard/BlackWizardAttackProjectile.cpp
  Source/SidheRigel/Character/Cold/ColdAttackProjectile.cpp
  Source/SidheRigel/Character/FairyWing/FairyWingAttackProjectile.cpp
  Source/SidheRigel/Character/Kerun/KerunAttackProjectile.cpp
  Source/SidheRigel/Dummy/DummyProjectile.cpp
  Source/SidheRigel/Dummy/DummyProjectile.h
  Source/SidheRigel/Minion/Minion.cpp
  Source/SidheRigel/Minion/Minion.h
  Source/SidheRigel/Minion/MinionProjectile.cpp
  Source/SidheRigel/Minion/MinionProjectile.h
  Source/SidheRigel/Tower/Tower.cpp
  Source/SidheRigel/Tower/TowerAttackProjectile.cpp
  Source/SidheRigel/Tower/TowerAttackProjectile.h
Labels: feature

#96 Develop minion gold fix
  Source/SidheRigel/Minion/Minion.cpp
  Source/SidheRigel/Minion/Minion.h
Labels: :lady_beetle: bug

#97 [Add] Character Die State
  Source/SidheRigel/SidheRigelCharacter.cpp
  Source/SidheRigel/SidheRigelCharacter.h
  Source/SidheRigel/State/DieState.cpp
  Source/SidheRigel/State/DieState.h
  Source/SidheRigel/State/StateMachine.cpp
  Source/SidheRigel/State/StateMachine.h
Labels: feature

#98 Develop skill range
  Content/Dummy/M_AssetPlatform.uasset
  Content/Dummy/SM_AssetPlatform.uasset
  Content/Heros/ACM/BP_ACMCharacter.uasset
  Content/Heros/BlackWizard/BP_BlackWizardCharacter.uasset
  Content/Heros/Cold/BP_ColdCharacter.uasset
  Content/Heros/FairyWIng/BP_FairyWingCharacter.uasset
  Content/Heros/Kerun/BP_KerunCharacter.uasset
  Content/Maps/Mainmenu.umap
  Content/TopDown/Blueprints/BP_TopDownCharacter.uasset
  Source/SidheRigel/Character/Cold/Skill/ColdESkill.cpp
  Source/SidheRigel/Character/Cold/Skill/ColdQSkill.cpp
  Source/SidheRigel/Character/Cold/Skill/ColdWSkill.cpp
  Source/SidheRigel/Character/Skill.cpp
  Source/SidheRigel/Character/Skill.h
  Source/SidheRigel/SidheRigelCharacter.cpp
  Source/SidheRigel/SidheRigelCharacter.h
  Source/SidheRigel/State/StateMachine.cpp
  Source/SidheRigel/State/UseSkillState.cpp
Labels: feature

#99 Develop attribute
  Source/SidheRigel/Character/Cold/ColdCharacter.cpp
  Source/SidheRigel/Character/Cold/ColdCharacter.h
  Source/SidheRigel/Character/Talent.h
  Source/SidheRigel/Character/TalentList.h
  Source/SidheRigel/SidheRigelCharacter.cpp
  Source/SidheRigel/SidheRigelCharacter.h
Labels: feature

#100 [Add] Minion Animation
  Content/Minion/ABP_Minion.uasset
  Content/Minion/BP_Minion.uasset
  Source/SidheRigel/Minion/Minion.cpp
  Source/SidheRigel/Minion/Minion.h
  Source/SidheRigel/Minion/MinionAnimInstance.cpp
  Source/SidheRigel/Minion/MinionAnimInstance.h
Labels: feature

#102 [Fix] Cant Damage TeamActor
  Source/SidheRigel/Character/Cold/Skill/ColdEDamageField.cpp
  Source/SidheRigel/Character/Cold/Skill/ColdWProjectile.cpp
Labels: :lady_beetle: bug

#103 Develop fog of war
  Content/Heros/BlackWizard/BP_BlackWizardCharacter.uasset
  Content/TopDown/Blueprints/BP_TopDownCharacter.uasset
  Content/__ExternalActors__/Maps/TrainingRoom/9/TV/Y36JDFMCGQAUO2RSRMACN8.uasset
Labels: feature

#104 Develop cold animation
  Content/Heros/Cold/ABP_ColdCharacter.uasset
  Source/SidheRigel/Character/Cold/ColdAnimInstance.cpp
  Source/SidheRigel/Character/Cold/ColdAnimInstance.h
  Source/SidheRigel/SidheRigelCharacter.h
  Source/SidheRigel/State/AttackState.cpp
  Source/SidheRigel/State/StateMachine.cpp
  Source/SidheRigel/State/StateMachine.h
Labels: feature

#106 [Fix] Character Turn to Target When Attack
  Source/SidheRigel/State/AttackState.cpp
Labels: :lady_beetle: bug

#112 Develop fairy wing
  Source/SidheRigel/Character/FairyWing/FairyWingCharacter.cpp
  Source/SidheRigel/Character/FairyWing/FairyWingCharacter.h
  Source/SidheRigel/Character/FairyWing/Skill/FairyWingEProjectile.cpp
  Source/SidheRigel/Character/FairyWing/Skill/FairyWingEProjectile.h
  Source/SidheRigel/Character/FairyWing/Skill/FairyWingESkill.cpp
  Source/SidheRigel/Character/FairyWing/Skill/FairyWingESkill.h
  Source/SidheRigel/Character/FairyWing/Skill/FairyWingQCollider.cpp
  Source/SidheRigel/Character/FairyWing/Skill/FairyWingQCollider.h
  Source/SidheRigel/Character/FairyWing/Skill/FairyWingQSkill.cpp
  Source/SidheRigel/Character/FairyWing/Skill/FairyWingQSkill.h
  Source/SidheRigel/Character/FairyWing/Skill/FairyWingRCollider.cpp
  Source/SidheRigel/Character/FairyWing/Skill/FairyWingRCollider.h
  Source/SidheRigel/Character/FairyWing/Skill/FairyWingRSkill.cpp
  Source/SidheRigel/Character/FairyWing/Skill/FairyWingRSkill.h
  Source/SidheRigel/Character/FairyWing/Skill/FairyWingWCollider.cpp
  Source/SidheRigel/Character/FairyWing/Skill/FairyWingWCollider.h
  Source/SidheRigel/Character/FairyWing/Skill/FairyWingWSkill.cpp
  Source/SidheRigel/Character/FairyWing/Skill/FairyWingWSkill.h
Labels: feature

#110 [Update] Minion Stop, Stun Implement
  Source/SidheRigel/Minion/Minion.cpp
  Source/SidheRigel/Minion/Minion.h
  Source/SidheRigel/Minion/MinionAIController.h
Labels: feature

#107 [Update] Minion Size Down
  Content/Minion/BP_Minion.uasset
Labels: feature

#108 [Fix] Minion Can Through Waypoint, Tower Block Move
  Content/Maps/Mainmenu.umap
  Content/Minion/BP_WayPoint.uasset
  Content/Tower/BP_Tower.uasset
  Content/Tower/S_Modular_Gate_Pillars_xfxoeigiy_lod0_Var1.uasset
  Content/__ExternalActors__/Maps/TrainingRoom/1/8F/JTYFG59001TH6FSGYP9KOO.uasset
  Content/__ExternalActors__/Maps/TrainingRoom/3/Y4/90Y0BGDT4XWOKUQ3Q1WHLQ.uasset
  Content/__ExternalActors__/Maps/TrainingRoom/6/8Z/46655D33N7LW1FZMY2HF4H.uasset
  Content/__ExternalActors__/Maps/TrainingRoom/B/48/7K50U1MMY3P1IRIAX2IXXS.uasset
  Content/__ExternalActors__/Maps/TrainingRoom/D/3E/QOVM6SP3YMJRLOGR00C0GU.uasset
  Source/SidheRigel/Tower/Tower.cpp
Labels: :lady_beetle: bug

#113 Implement Kerun Skill And Change Skill to USkill
  Source/SidheRigel/Character/BlackWizard/BlackWizardCharacter.cpp
  Source/SidheRigel/Character/BlackWizard/Skill/BlackWizardESkill.cpp
  Source/SidheRigel/Character/BlackWizard/Skill/BlackWizardESkill.h
  Source/SidheRigel/Character/BlackWizard/Skill/BlackWizardQSkill.cpp
  Source/SidheRigel/Character/BlackWizard/Skill/BlackWizardQSkill.h
  Source/SidheRigel/Character/BlackWizard/Skill/BlackWizardRSkill.cpp
  Source/SidheRigel/Character/BlackWizard/Skill/BlackWizardRSkill.h
  Source/SidheRigel/Character/BlackWizard/Skill/BlackWizardWSkill.cpp
  Source/SidheRigel/Character/BlackWizard/Skill/BlackWizardWSkill.h
  Source/SidheRigel/Character/Cold/ColdCharacter.cpp
  Source/SidheRigel/Character/Cold/Skill/ColdESkill.cpp
  Source/SidheRigel/Character/Cold/Skill/ColdESkill.h
  Source/SidheRigel/Character/Cold/Skill/ColdQSkill.cpp
  Source/SidheRigel/Character/Cold/Skill/ColdQSkill.h
  Source/SidheRigel/Character/Cold/Skill/ColdR1Skill.cpp
  Source/SidheRigel/Character/Cold/Skill/ColdR1Skill.h
  Source/SidheRigel/Character/Cold/Skill/ColdR2Skill.cpp
  Source/SidheRigel/Character/Cold/Skill/ColdR2Skill.h
  Source/SidheRigel/Character/Cold/Skill/ColdWSkill.cpp
  Source/SidheRigel/Character/Cold/Skill/ColdWSkill.h
  Source/SidheRigel/Character/FairyWing/FairyWingCharacter.cpp
  Source/SidheRigel/Character/FairyWing/Skill/FairyWingESkill.cpp
  Source/SidheRigel/Character/FairyWing/Skill/FairyWingESkill.h
  Source/SidheRigel/Character/FairyWing/Skill/FairyWingQSkill.cpp
  Source/SidheRigel/Character/FairyWing/Skill/FairyWingQSkill.h
  Source/SidheRigel/Character/FairyWing/Skill/FairyWingRSkill.cpp
  Source/SidheRigel/Character/FairyWing/Skill/FairyWingRSkill.h
  Source/SidheRigel/Character/FairyWing/Skill/FairyWingWSkill.cpp
  Source/SidheRigel/Character/FairyWing/Skill/FairyWingWSkill.h
  Source/SidheRigel/Character/Kerun/KerunCharacter.cpp
  Source/SidheRigel/Character/Kerun/KerunCharacter.h
  Source/SidheRigel/Character/Kerun/Skills/KerunQSkill.cpp
  Source/SidheRigel/Character/Kerun/Skills/KerunQSkill.h
  Source/SidheRigel/Character/Kerun/Skills/KerunR1Skill.cpp
  Source/SidheRigel/Character/Kerun/Skills/KerunR1Skill.h
  Source/SidheRigel/Character/Kerun/Skills/KerunWSkill.cpp
  Source/SidheRigel/Character/Kerun/Skills/KerunWSkill.h
  Source/SidheRigel/Character/Skill.cpp
  Source/SidheRigel/Character/Skill.h
  Source/SidheRigel/SidheRigelCharacter.cpp
  Source/SidheRigel/SidheRigelCharacter.h
Labels: feature

#114 [Fix] Show Mouse Cursor
  Source/SidheRigel/SidheRigelGameInstance.cpp
Labels: :lady_beetle: bug

#115 Develop move vector
  Source/SidheRigel/Character/Cold/Skill/ColdWSkill.h
  Source/SidheRigel/Minion/Minion.cpp
  Source/SidheRigel/SidheRigelCharacter.cpp
Labels: :lady_beetle: bug

#116 Develop black minion
  Content/Maps/Mainmenu.umap
  Content/Minion/Minion_Lane_Melee_Dusk.uasset
  Content/__ExternalActors__/Maps/TrainingRoom/2/9E/ZI5P8YZ5Q13UK9K9JO9L9X.uasset
  Content/__ExternalActors__/Maps/TrainingRoom/8/BX/KK0PKLSBCS50IVJIYZKNHT.uasset
  Source/SidheRigel/Minion/MinionSpawner.cpp
  Source/SidheRigel/Minion/MinionSpawner.h
Labels: feature

#117 [Fix] Cant Attack Twice
  Content/Heros/Cold/Skill/BP_ColdWParticle.uasset
  Content/Heros/Cold/Skill/BP_ColdWProjectile.uasset
  Content/Heros/Cold/Skill/P_Murdock_Spreadshot.uasset
  Source/SidheRigel/Character/Cold/Skill/ColdWParticle.cpp
  Source/SidheRigel/Character/Cold/Skill/ColdWParticle.h
  Source/SidheRigel/Character/Cold/Skill/ColdWSkill.cpp
  Source/SidheRigel/Character/Cold/Skill/ColdWSkill.h
Labels: :lady_beetle: bug, feature
