Repository SR-PLUM/SidheRigel, pull requests merged in 2023-09, with the labels that each got.

#54 Develop acm
  Content/Heros/ACM/BP_ACMAttackProjectile.uasset
  Content/Heros/ACM/Skills/BP_ACMECollider.uasset
  Content/Heros/ACM/Skills/BP_ACMQCollider.uasset
  Content/Heros/ACM/Skills/M_ACMQMaterial.uasset
  Content/Heros/ACM/Skills/SM_ACMECollider.uasset
  Content/Heros/ACM/Skills/SM_ACMQCollider.uasset
  Source/SidheRigel/Character/ACM/ACMAttackProjectile.cpp
  Source/SidheRigel/Character/ACM/ACMAttackProjectile.h
  Source/SidheRigel/Character/ACM/ACMCharacter.cpp
  Source/SidheRigel/Character/ACM/ACMCharacter.h
  Source/SidheRigel/Character/ACM/Skills/ACMECollider.cpp
  Source/SidheRigel/Character/ACM/Skills/ACMECollider.h
  Source/SidheRigel/Character/ACM/Skills/ACMQCollider.cpp
  Source/SidheRigel/Character/ACM/Skills/ACMQCollider.h
Labels: feature

#55 Develop base character
  Config/DefaultInput.ini
  Source/SidheRigel/Character/ACM/ACMCharacter.cpp
  Source/SidheRigel/Character/ACM/ACMCharacter.h
  Source/SidheRigel/Character/BlackWizard/BlackWizardCharacter.cpp
  Source/SidheRigel/Character/BlackWizard/BlackWizardCharacter.h
  Source/SidheRigel/Character/Cold/ColdCharacter.cpp
  Source/SidheRigel/Character/Cold/ColdCharacter.h
  Source/SidheRigel/Character/FairyWing/FairyWingCharacter.cpp
  Source/SidheRigel/Character/FairyWing/FairyWingCharacter.h
  Source/SidheRigel/Character/Kerun/KerunCharacter.cpp
  Source/SidheRigel/Character/Kerun/KerunCharacter.h
  Source/SidheRigel/SidheRigelCharacter.cpp
  Source/SidheRigel/SidheRigelCharacter.h
  Source/SidheRigel/SidheRigelPlayerController.cpp
  Source/SidheRigel/SidheRigelPlayerController.h
  Source/SidheRigel/State/Attack/AttackState.cpp
  Source/SidheRigel/State/Attack/AttackState.h
  Source/SidheRigel/State/Attack/AttackStateMachine.cpp
  Source/SidheRigel/State/Attack/AttackStateMachine.h
  Source/SidheRigel/State/Attack/DoAttackState.cpp
  Source/SidheRigel/State/Attack/DoAttackState.h
  Source/SidheRigel/State/Attack/MoveToAttackState.cpp
  Source/SidheRigel/State/Attack/MoveToAttackState.h
  Source/SidheRigel/State/Attack/WaitAttackState.cpp
  Source/SidheRigel/State/Attack/WaitAttackState.h
  Source/SidheRigel/State/AttackState.cpp
  Source/SidheRigel/State/AttackState.h
  Source/SidheRigel/State/AttackWaitState.cpp
  Source/SidheRigel/State/AttackWaitState.h
  Source/SidheRigel/State/IdleState.cpp
  Source/SidheRigel/State/IdleState.h
  Source/SidheRigel/State/MoveState.cpp
  Source/SidheRigel/State/MoveState.h
  Source/SidheRigel/State/MoveToAttackState.cpp
  Source/SidheRigel/State/MoveToAttackState.h
  Source/SidheRigel/State/SkillReadyState.cpp
  Source/SidheRigel/State/SkillReadyState.h
  Source/SidheRigel/State/State.cpp
  Source/SidheRigel/State/State.h
  Source/SidheRigel/State/StateMachine.cpp
  Source/SidheRigel/State/StateMachine.h
  Source/SidheRigel/State/UseSkillState.cpp
  Source/SidheRigel/State/UseSkillState.h
Labels: Refactor

#60 Develop lobby
  Config/DefaultEngine.ini
  Content/Maps/Lobby.umap
  Content/UIBlueprints/WBP_LobbyMenu.uasset
  Source/SidheRigel/Lobby/LobbyGameMode.cpp
  Source/SidheRigel/Lobby/LobbyGameMode.h
  Source/SidheRigel/Lobby/LobbyMenu.cpp
  Source/SidheRigel/Lobby/LobbyMenu.h
  Source/SidheRigel/SidheRigelGameInstance.cpp
  Source/SidheRigel/SidheRigelGameInstance.h
  Source/SidheRigel/SidheRigelGameMode.cpp
  Source/SidheRigel/SidheRigelGameMode.h
Labels: feature

#63 [Refactor] Refactor Skill Struct
  Source/SidheRigel/Character/Cold/ColdCharacter.cpp
  Source/SidheRigel/Character/Cold/ColdCharacter.h
  Source/SidheRigel/Character/Cold/Skill/ColdEDamageField.cpp
  Source/SidheRigel/Character/Cold/Skill/ColdEDamageField.h
  Source/SidheRigel/Character/Cold/Skill/ColdESkill.cpp
  Source/SidheRigel/Character/Cold/Skill/ColdESkill.h
  Source/SidheRigel/Character/Cold/Skill/ColdQProjectile.cpp
  Source/SidheRigel/Character/Cold/Skill/ColdQProjectile.h
  Source/SidheRigel/Character/Cold/Skill/ColdQSkill.cpp
  Source/SidheRigel/Character/Cold/Skill/ColdQSkill.h
  Source/SidheRigel/Character/Cold/Skill/ColdR1Projectile.cpp
  Source/SidheRigel/Character/Cold/Skill/ColdR1Projectile.h
  Source/SidheRigel/Character/Cold/Skill/ColdR1Skill.cpp
  Source/SidheRigel/Character/Cold/Skill/ColdR1Skill.h
  Source/SidheRigel/Character/Cold/Skill/ColdR2Projectile.cpp
  Source/SidheRigel/Character/Cold/Skill/ColdR2Projectile.h
  Source/SidheRigel/Character/Cold/Skill/ColdR2Skill.cpp
  Source/SidheRigel/Character/Cold/Skill/ColdR2Skill.h
  Source/SidheRigel/Character/Cold/Skill/ColdWProjectile.cpp
  Source/SidheRigel/Character/Cold/Skill/ColdWProjectile.h
  Source/SidheRigel/Character/Cold/Skill/ColdWSkill.cpp
  Source/SidheRigel/Character/Cold/Skill/ColdWSkill.h
  Source/SidheRigel/Character/Skill.cpp
  Source/SidheRigel/Character/Skill.h
  Source/SidheRigel/SidheRigelCharacter.cpp
  Source/SidheRigel/SidheRigelCharacter.h
  Source/SidheRigel/State/AttackState.cpp
  Source/SidheRigel/State/AttackWaitState.cpp
  Source/SidheRigel/State/IdleState.cpp
  Source/SidheRigel/State/MoveState.cpp
  Source/SidheRigel/State/MoveToAttackState.cpp
  Source/SidheRigel/State/SkillReadyState.cpp
  Source/SidheRigel/State/UseSkillState.cpp
Labels: Refactor

#64 [Add] Implement Stun
  Source/SidheRigel/SidheRigelCharacter.cpp
  Source/SidheRigel/SidheRigelPlayerController.cpp
  Source/SidheRigel/State/StateMachine.cpp
  Source/SidheRigel/State/StateMachine.h
  Source/SidheRigel/State/StopState.cpp
  Source/SidheRigel/State/StopState.h
  Source/SidheRigel/State/StunState.cpp
  Source/SidheRigel/State/StunState.h
Labels: feature

#65 [Refactor] Refactoring StateMachine
  Source/SidheRigel/State/AttackState.cpp
  Source/SidheRigel/State/AttackWaitState.cpp
  Source/SidheRigel/State/IdleState.cpp
  Source/SidheRigel/State/MoveState.cpp
  Source/SidheRigel/State/MoveToAttackState.cpp
  Source/SidheRigel/State/SkillReadyState.cpp
  Source/SidheRigel/State/SkillReadyState.h
  Source/SidheRigel/State/StateMachine.cpp
  Source/SidheRigel/State/StateMachine.h
  Source/SidheRigel/State/UseSkillState.cpp
Labels: Refactor

#67 Develop in game UI
  Content/TopDown/Maps/TopDownMap.umap
  Content/UIBlueprints/InGameUI/WBP_CharacterStatus.uasset
  Content/UIBlueprints/InGameUI/WBP_CombatSummary.uasset
  Content/UIBlueprints/InGameUI/WBP_InGameUI.uasset
  Content/UIBlueprints/InGameUI/WBP_ItemSlot.uasset
  Source/SidheRigel/InGameMapScriptActor.cpp
  Source/SidheRigel/InGameMapScriptActor.h
  Source/SidheRigel/Lobby/LobbyMenu.cpp
  Source/SidheRigel/SidheRigel.Build.cs
  Source/SidheRigel/SidheRigelGameInstance.h
  Source/SidheRigel/UI/CharacterStatus.cpp
  Source/SidheRigel/UI/CharacterStatus.h
  Source/SidheRigel/UI/InGameUI.cpp
  Source/SidheRigel/UI/InGameUI.h
Labels: :lady_beetle: bug, feature
