Repository SR-PLUM/SidheRigel, pull requests merged in 2023-08, with the labels that each got.

#44 [Add] MainMenu UI
  Config/DefaultEngine.ini
  Content/Maps/Mainmenu.umap
  Content/UIBlueprints/WBP_Mainmenu.uasset
  SidheRigel.uproject
  Source/SidheRigel/MainMenu/MainMenu.cpp
  Source/SidheRigel/MainMenu/MainMenu.h
  Source/SidheRigel/MainMenu/MenuInterface.cpp
  Source/SidheRigel/MainMenu/MenuInterface.h
  Source/SidheRigel/SidheRigel.Build.cs
  Source/SidheRigel/SidheRigelGameInstance.cpp
  Source/SidheRigel/SidheRigelGameInstance.h
Labels: feature

#46 Develop main menu
  Config/DefaultEngine.ini
  Content/TopDown/Maps/TopDownMap.umap
  Content/UIBlueprints/WBP_InGameMenu.uasset
  Content/UIBlueprints/WBP_Mainmenu.uasset
  Content/UIBlueprints/WBP_ServerRow.uasset
  SidheRigel.uproject
  Source/SidheRigel/MainMenu/InGameMenu.cpp
  Source/SidheRigel/MainMenu/InGameMenu.h
  Source/SidheRigel/MainMenu/MainMenu.cpp
  Source/SidheRigel/MainMenu/MainMenu.h
  Source/SidheRigel/MainMenu/MenuInterface.h
  Source/SidheRigel/MainMenu/MenuWidget.cpp
  Source/SidheRigel/MainMenu/MenuWidget.h
  Source/SidheRigel/MainMenu/ServerRow.cpp
  Source/SidheRigel/MainMenu/ServerRow.h
  Source/SidheRigel/SidheRigel.Build.cs
  Source/SidheRigel/SidheRigelGameInstance.cpp
  Source/SidheRigel/SidheRigelGameInstance.h
Labels: feature

#47 [Debug] Steam Multiplay Host Debugging
  Config/DefaultEngine.ini
Labels: :lady_beetle: bug

#48 Develop steam multiplay host debugging
  Content/__ExternalActors__/TopDown/Maps/TopDownMap/4/56/3ZRVIKL3HVPV6XKBLTG28N.uasset
  Content/__ExternalActors__/TopDown/Maps/TopDownMap/9/HT/GIKW02BYVNH6W40PVGMY0Y.uasset
  Content/__ExternalActors__/TopDown/Maps/TopDownMap/A/AS/30VXO5DYCEOEZMFUTGEUYU.uasset
  Content/__ExternalActors__/TopDown/Maps/TopDownMap/C/05/ZPZSXPXJDU2K89LN7L0YYT.uasset
  Content/__ExternalActors__/TopDown/Maps/TopDownMap/E/RZ/VSBFMQDYWVJRLIKY9QLLQA.uasset
  Source/SidheRigel/SidheRigelGameInstance.cpp
  Source/SidheRigel/SidheRigelGameInstance.h
Labels: :lady_beetle: bug

#49 Develop main menu
  Content/UIBlueprints/WBP_Mainmenu.uasset
  Content/UIBlueprints/WBP_ServerRow.uasset
  Source/SidheRigel/MainMenu/MainMenu.cpp
  Source/SidheRigel/MainMenu/MainMenu.h
  Source/SidheRigel/MainMenu/MenuInterface.h
  Source/SidheRigel/MainMenu/ServerRow.h
  Source/SidheRigel/SidheRigelGameInstance.cpp
  Source/SidheRigel/SidheRigelGameInstance.h
Labels: :lady_beetle: bug, feature

#51 Develop cold
  Content/Heros/Cold/Skill/BP_ColdEDamageField.uasset
  Content/Heros/Cold/Skill/BP_ColdEProjectile.uasset
  Content/Heros/Cold/Skill/SM_ColdEDamageField.uasset
  Content/Heros/Cold/Skill/SM_ColdEProjectile.uasset
  Content/__ExternalActors__/TopDown/Maps/TopDownMap/4/56/3ZRVIKL3HVPV6XKBLTG28N.uasset
  Content/__ExternalActors__/TopDown/Maps/TopDownMap/9/HT/GIKW02BYVNH6W40PVGMY0Y.uasset
  Content/__ExternalActors__/TopDown/Maps/TopDownMap/A/AS/30VXO5DYCEOEZMFUTGEUYU.uasset
  Content/__ExternalActors__/TopDown/Maps/TopDownMap/C/05/ZPZSXPXJDU2K89LN7L0YYT.uasset
  Content/__ExternalActors__/TopDown/Maps/TopDownMap/E/RZ/VSBFMQDYWVJRLIKY9QLLQA.uasset
  Source/SidheRigel/Character/Cold/ColdCharacter.cpp
  Source/SidheRigel/Character/Cold/ColdCharacter.h
  Source/SidheRigel/Character/Cold/Skill/ColdEDamageField.cpp
  Source/SidheRigel/Character/Cold/Skill/ColdEDamageField.h
  Source/SidheRigel/Character/Cold/Skill/ColdEProjectile.cpp
  Source/SidheRigel/Character/Cold/Skill/ColdEProjectile.h
Labels: feature

#52 [Add] Defence System
  Source/SidheRigel/SidheRigelCharacter.cpp
  Source/SidheRigel/SidheRigelCharacter.h
Labels: feature

#53 [Add] BlackWizard Q, E Skill Implement
  Content/Heros/BlackWizard/Skill/BP_BlackWizardECollider.uasset
  Content/Heros/BlackWizard/Skill/BP_BlackWizardQCollider.uasset
  Content/Heros/BlackWizard/Skill/SM_BlackWizardECollider.uasset
  Content/Heros/BlackWizard/Skill/SM_BlackWizardQCollider.uasset
  Source/SidheRigel/Character/BlackWizard/BlackWizardCharacter.cpp
  Source/SidheRigel/Character/BlackWizard/BlackWizardCharacter.h
  Source/SidheRigel/Character/BlackWizard/Skill/BlackWizardECollider.cpp
  Source/SidheRigel/Character/BlackWizard/Skill/BlackWizardECollider.h
  Source/SidheRigel/Character/BlackWizard/Skill/BlackWizardQCollider.cpp
  Source/SidheRigel/Character/BlackWizard/Skill/BlackWizardQCollider.h
Labels: feature
