Repository SR-PLUM/SidheRigel, pull requests merged in 2023-05, with the labels that each got.

#15 Develop attack
  Config/DefaultInput.ini
  Content/Dummy/BP_Dummy.uasset
  Content/Dummy/BP_DummyProjectile.uasset
  Content/Dummy/MaterialSphere.uasset
  Content/Heros/ACM/BP_ACMCharacter.uasset
  Content/TopDown/Blueprints/BP_TopDownCharacter.uasset
  Content/__ExternalActors__/TopDown/Maps/TopDownMap/A/9C/3S8LA7VCD6ZBRC731IDK2Q.uasset
  Content/__ExternalActors__/TopDown/Maps/TopDownMap/A/BS/3UJ7KLRQESVKRU57942NPG.uasset
  Source/SidheRigel/Dummy/Dummy.cpp
  Source/SidheRigel/Dummy/DummyProjectile.cpp
  Source/SidheRigel/Dummy/DummyProjectile.h
  Source/SidheRigel/Interface/Attackable.h
  Source/SidheRigel/SidheRigelCharacter.cpp
  Source/SidheRigel/SidheRigelCharacter.h
  Source/SidheRigel/SidheRigelPlayerController.cpp
  Source/SidheRigel/SidheRigelPlayerController.h
Labels: :lady_beetle: bug, feature

#17 Develop attack
  Config/DefaultInput.ini
  Source/SidheRigel/SidheRigelCharacter.cpp
  Source/SidheRigel/SidheRigelCharacter.h
  Source/SidheRigel/SidheRigelPlayerController.cpp
  Source/SidheRigel/SidheRigelPlayerController.h
Labels: feature

#19 [Add] Implement LeftMouseButton Function
  Source/SidheRigel/Character/Cold/ColdCharacter.cpp
  Source/SidheRigel/Character/Cold/ColdCharacter.h
  Source/SidheRigel/SidheRigelCharacter.cpp
  Source/SidheRigel/SidheRigelCharacter.h
  Source/SidheRigel/SidheRigelPlayerController.cpp
Labels: :lady_beetle: bug, feature, Refactor

#23 [Add] Implement HP, GenerateHP
  Source/SidheRigel/SidheRigelCharacter.cpp
  Source/SidheRigel/SidheRigelCharacter.h
Labels: feature

#27 [Add] Implement LifeSteal
  Source/SidheRigel/Character/Cold/ColdCharacter.cpp
  Source/SidheRigel/Character/Cold/Skill/ColdQProjectile.cpp
  Source/SidheRigel/Character/Cold/Skill/ColdQProjectile.h
  Source/SidheRigel/Character/Kerun/KerunAttackProjectile.cpp
  Source/SidheRigel/Dummy/Dummy.cpp
  Source/SidheRigel/Dummy/Dummy.h
  Source/SidheRigel/Dummy/DummyProjectile.cpp
  Source/SidheRigel/Dummy/DummyProjectile.h
  Source/SidheRigel/Interface/Damagable.h
  Source/SidheRigel/SidheRigelCharacter.cpp
  Source/SidheRigel/SidheRigelCharacter.h
Labels: feature

#28 Develop kerun
  Content/Heros/Kerun/Animations/Melee_A_Montage.uasset
  Content/Heros/Kerun/BP_KerunAttackProjectile.uasset
  Source/SidheRigel/Character/Kerun/KerunAttackProjectile.cpp
  Source/SidheRigel/Character/Kerun/KerunAttackProjectile.h
  Source/SidheRigel/Character/Kerun/KerunCharacter.cpp
  Source/SidheRigel/Character/Kerun/KerunCharacter.h
  Source/SidheRigel/Character/Kerun/Skills/KerunQSkill.cpp
  Source/SidheRigel/Character/Kerun/Skills/KerunQSkill.h
  Source/SidheRigel/SidheRigelCharacter.cpp
Labels: feature

#29 [Add] Implement Cold Q
  Content/Heros/Cold/Skill/BP_ColdQProjectile.uasset
  Content/Heros/Cold/Skill/M_ColdQProjectile.uasset
  Content/Heros/Cold/Skill/SM_ColdQProjectile.uasset
  Source/SidheRigel/Character/Cold/ColdCharacter.cpp
  Source/SidheRigel/Character/Cold/ColdCharacter.h
Labels: feature, Refactor

#34 [Add] FairyWing E Skill Implement
  Content/Heros/FairyWIng/BP_FairyWingAttackProjectile.uasset
  Content/Heros/FairyWIng/SM_FairyWingAttackProjectile.uasset
  Content/Heros/FairyWIng/Skill/BP_FairyWingEProjectile.uasset
  Content/Heros/FairyWIng/Skill/SM_FairyWingEProjectile.uasset
  Source/SidheRigel/Character/FairyWing/FairyWingAttackProjectile.cpp
  Source/SidheRigel/Character/FairyWing/FairyWingAttackProjectile.h
  Source/SidheRigel/Character/FairyWing/FairyWingCharacter.cpp
  Source/SidheRigel/Character/FairyWing/FairyWingCharacter.h
  Source/SidheRigel/Character/FairyWing/Skill/FairyWingEProjectile.cpp
  Source/SidheRigel/Character/FairyWing/Skill/FairyWingEProjectile.h
Labels: feature

#37 [Add] FairyWing Q Skill implement
  Content/Heros/FairyWIng/Skill/BP_FairyWingQCollider.uasset
  Content/Heros/FairyWIng/Skill/SM_FairyWingQCollider.uasset
  Source/SidheRigel/Character/FairyWing/FairyWingCharacter.cpp
  Source/SidheRigel/Character/FairyWing/FairyWingCharacter.h
  Source/SidheRigel/Character/FairyWing/Skill/FairyWingQCollider.cpp
  Source/SidheRigel/Character/FairyWing/Skill/FairyWingQCollider.h
Labels: feature
