Repository SR-PLUM/SidheRigel, pull requests merged in 2023-11, with the labels that each got.

#118 Develop fix skill problem
  Source/SidheRigel/Character/BlackWizard/Skill/BlackWizardESkill.cpp
  Source/SidheRigel/Character/BlackWizard/Skill/BlackWizardQSkill.cpp
  Source/SidheRigel/Character/BlackWizard/Skill/BlackWizardRSkill.cpp
  Source/SidheRigel/Character/BlackWizard/Skill/BlackWizardWSkill.cpp
  Source/SidheRigel/Character/Cold/ColdCharacter.cpp
  Source/SidheRigel/Character/Cold/Skill/ColdESkill.cpp
  Source/SidheRigel/Character/Cold/Skill/ColdQSkill.cpp
  Source/SidheRigel/Character/Cold/Skill/ColdR1Skill.cpp
  Source/SidheRigel/Character/Cold/Skill/ColdR2Skill.cpp
  Source/SidheRigel/Character/Cold/Skill/ColdWSkill.cpp
  Source/SidheRigel/Character/FairyWing/FairyWingCharacter.cpp
  Source/SidheRigel/Character/FairyWing/Skill/FairyWingESkill.cpp
  Source/SidheRigel/Character/FairyWing/Skill/FairyWingQSkill.cpp
  Source/SidheRigel/Character/FairyWing/Skill/FairyWingRSkill.cpp
  Source/SidheRigel/Character/FairyWing/Skill/FairyWingWSkill.cpp
  Source/SidheRigel/Character/Kerun/Skills/KerunQSkill.cpp
  Source/SidheRigel/Character/Kerun/Skills/KerunQSkill.h
  Source/SidheRigel/Character/Kerun/Skills/KerunR1Skill.cpp
  Source/SidheRigel/Character/Kerun/Skills/KerunWSkill.cpp
  Source/SidheRigel/Character/Kerun/Skills/KerunWSkill.h
  Source/SidheRigel/Character/Skill.cpp
  Source/SidheRigel/Character/Skill.h
  Source/SidheRigel/SidheRigelCharacter.cpp
  Source/SidheRigel/SidheRigelCharacter.h
Labels: :lady_beetle: bug

#122 [Update] Require Mana When Using Skill
  Source/SidheRigel/Character/Cold/Skill/ColdESkill.cpp
  Source/SidheRigel/Character/Cold/Skill/ColdQSkill.cpp
  Source/SidheRigel/Character/Cold/Skill/ColdWSkill.cpp
  Source/SidheRigel/Character/Skill.cpp
  Source/SidheRigel/Character/Skill.h
  Source/SidheRigel/SidheRigelCharacter.cpp
  Source/SidheRigel/SidheRigelCharacter.h
  Source/SidheRigel/State/StateMachine.cpp
Labels: feature

#128 Develop cold talent
  Content/Heros/Cold/Skill/BP_ColdEDamageField.uasset
  Content/Heros/Cold/Skill/BP_ColdEGroundFireEffect.uasset
  Content/Heros/Cold/Skill/BP_ColdQSplash.uasset
  Content/Heros/Cold/Skill/P_ColdEDamageField1.uasset
  Content/Heros/Cold/Skill/P_ColdEDamageField2.uasset
  Content/Heros/Cold/Skill/P_ColdEDamageField3.uasset
  Content/Heros/Cold/Skill/P_ColdEGroundFire.uasset
  Content/Heros/Cold/Skill/P_ColdETarget.uasset
  Content/Heros/Cold/Skill/P_ColdQSplash.uasset
  Source/SidheRigel/Character/Cold/ColdCharacter.cpp
  Source/SidheRigel/Character/Cold/Skill/ColdEDamageField.cpp
  Source/SidheRigel/Character/Cold/Skill/ColdEGroundFireEffect.cpp
  Source/SidheRigel/Character/Cold/Skill/ColdEGroundFireEffect.h
  Source/SidheRigel/Character/Cold/Skill/ColdEProjectile.cpp
  Source/SidheRigel/Character/Cold/Skill/ColdESkill.cpp
  Source/SidheRigel/Character/Cold/Skill/ColdESkill.h
  Source/SidheRigel/Character/Cold/Skill/ColdQProjectile.cpp
  Source/SidheRigel/Character/Cold/Skill/ColdQProjectile.h
  Source/SidheRigel/Character/Cold/Skill/ColdQSplash.cpp
  Source/SidheRigel/Character/Cold/Skill/ColdQSplash.h
  Source/SidheRigel/Character/Cold/Skill/ColdWSkill.cpp
  Source/SidheRigel/Character/Skill.cpp
  Source/SidheRigel/Character/Skill.h
  Source/SidheRigel/State/State.h
Labels: feature

#130 Develop fairy wing Talent
  Source/SidheRigel/Character/FairyWing/FairyWingCharacter.cpp
  Source/SidheRigel/Character/FairyWing/FairyWingCharacter.h
  Source/SidheRigel/Character/FairyWing/Skill/FairyWingEProjectile.cpp
  Source/SidheRigel/Character/FairyWing/Skill/FairyWingEProjectile.h
  Source/SidheRigel/Character/FairyWing/Skill/FairyWingESkill.cpp
  Source/SidheRigel/Character/FairyWing/Skill/FairyWingESkill.h
  Source/SidheRigel/Character/FairyWing/Skill/FairyWingQCollider.cpp
  Source/SidheRigel/Character/FairyWing/Skill/FairyWingQCollider.h
  Source/SidheRigel/Character/FairyWing/Skill/FairyWingQSkill.cpp
  Source/SidheRigel/Character/FairyWing/Skill/FairyWingQSkill.h
  Source/SidheRigel/Character/FairyWing/Skill/FairyWingRCollider.cpp
  Source/SidheRigel/Character/FairyWing/Skill/FairyWingRCollider.h
  Source/SidheRigel/Character/FairyWing/Skill/FairyWingRSkill.cpp
  Source/SidheRigel/Character/FairyWing/Skill/FairyWingRSkill.h
  Source/SidheRigel/Character/FairyWing/Skill/FairyWingWCollider.cpp
  Source/SidheRigel/Character/FairyWing/Skill/FairyWingWCollider.h
  Source/SidheRigel/Character/FairyWing/Skill/FairyWingWSkill.cpp
  Source/SidheRigel/Character/FairyWing/Skill/FairyWingWSkill.h
  Source/SidheRigel/Character/Skill.h
  Source/SidheRigel/SidheRigelCharacter.h
Labels: feature

#131 [Update] Change StateMachineTimer to FTimerHandle
  Source/SidheRigel/SidheRigelCharacter.cpp
  Source/SidheRigel/SidheRigelCharacter.h
  Source/SidheRigel/SidheRigelPlayerController.cpp
  Source/SidheRigel/State/StateMachine.cpp
  Source/SidheRigel/State/StateMachine.h
Labels: feature, Refactor

#132 Develop cold animation
  Content/Heros/Cold/ABP_ColdCharacter.uasset
  Content/Heros/Cold/Animation/Attack.uasset
  Content/Heros/Cold/Animation/Eskill.uasset
  Content/Heros/Cold/Animation/Qskill.uasset
  Content/Heros/Cold/Animation/Rskill.uasset
  Content/Heros/Cold/Animation/Wskill.uasset
  Source/SidheRigel/Character/Cold/ColdAnimInstance.cpp
  Source/SidheRigel/Character/Cold/ColdAnimInstance.h
  Source/SidheRigel/Character/Cold/Skill/ColdR2Skill.cpp
  Source/SidheRigel/Character/Cold/Skill/ColdWSkill.h
  Source/SidheRigel/State/UseSkillState.cpp
Labels: feature

#134 Develop kerun
  SidheRigel.uproject
  Source/SidheRigel/Character/Kerun/KerunAttackProjectile.cpp
  Source/SidheRigel/Character/Kerun/KerunCharacter.cpp
  Source/SidheRigel/Character/Kerun/KerunCharacter.h
  Source/SidheRigel/Character/Kerun/Skills/KerunESkillTalentQuest.cpp
  Source/SidheRigel/Character/Kerun/Skills/KerunESkillTalentQuest.h
  Source/SidheRigel/Character/Kerun/Skills/KerunQSkill.cpp
  Source/SidheRigel/Character/Kerun/Skills/KerunQSkill.h
  Source/SidheRigel/Character/Kerun/Skills/KerunQSkillTalentQuest.cpp
  Source/SidheRigel/Character/Kerun/Skills/KerunQSkillTalentQuest.h
  Source/SidheRigel/Character/Kerun/Skills/KerunWSkill.cpp
  Source/SidheRigel/Character/Kerun/Skills/KerunWSkill.h
  Source/SidheRigel/Character/Kerun/Skills/KerunWSkillTalentQuest.cpp
  Source/SidheRigel/Character/Kerun/Skills/KerunWSkillTalentQuest.h
  Source/SidheRigel/Character/TalentQuest.cpp
  Source/SidheRigel/Character/TalentQuest.h
  Source/SidheRigel/Dummy/DummyProjectile.cpp
  Source/SidheRigel/Minion/Minion.h
  Source/SidheRigel/SidheRigelCharacter.cpp
  Source/SidheRigel/SidheRigelCharacter.h
  Source/SidheRigel/State/MoveState.cpp
  Source/SidheRigel/State/State.h
  Source/SidheRigel/UI/TalentItem.cpp
Labels: feature

#133 Develop fairy wing Talent
  Source/SidheRigel/Character/FairyWing/FairyWingCharacter.cpp
  Source/SidheRigel/Character/FairyWing/Skill/FairyWingEProjectile.cpp
  Source/SidheRigel/Character/FairyWing/Skill/FairyWingEProjectile.h
  Source/SidheRigel/Character/FairyWing/Skill/FairyWingESkill.cpp
  Source/SidheRigel/Character/FairyWing/Skill/FairyWingESkill.h
  Source/SidheRigel/Character/FairyWing/Skill/FairyWingQCollider.cpp
  Source/SidheRigel/Character/FairyWing/Skill/FairyWingQSkill.cpp
  Source/SidheRigel/Character/FairyWing/Skill/FairyWingQSkill.h
  Source/SidheRigel/Character/FairyWing/Skill/FairyWingWCollider.cpp
  Source/SidheRigel/Character/FairyWing/Skill/FairyWingWCollider.h
  Source/SidheRigel/Character/FairyWing/Skill/FairyWingWSkill.cpp
  Source/SidheRigel/Character/FairyWing/Skill/FairyWingWSkill.h
  Source/SidheRigel/Character/Skill.h
  Source/SidheRigel/SidheRigelCharacter.cpp
  Source/SidheRigel/SidheRigelCharacter.h
Labels: feature

#135 [Update] ReduceHeal
  Source/SidheRigel/SidheRigelCharacter.cpp
  Source/SidheRigel/SidheRigelCharacter.h
Labels: feature

#136 [Fix] Minion, Tower Attack Damage 0 Bug
  Source/SidheRigel/Minion/Minion.cpp
  Source/SidheRigel/Tower/Tower.cpp
Labels: :lady_beetle: bug

#137 [Update] MinionWave
  Content/Minion/ABP_RangeMinion.uasset
  Content/Minion/BP_Minion.uasset
  Content/Minion/BP_RangeMinion.uasset
  Content/Minion/Minion_Lane_Melee_Dusk.uasset
  Content/Minion/Minion_Lane_Ranged_Dawn.uasset
  Content/Minion/Minion_Lane_Ranged_Dusk.uasset
  Content/Minion/Minion_Lane_Siege_Dawn.uasset
  Content/Minion/Minion_Lane_Siege_Dusk.uasset
  Content/__ExternalActors__/Maps/TrainingRoom/2/9E/ZI5P8YZ5Q13UK9K9JO9L9X.uasset
  Content/__ExternalActors__/Maps/TrainingRoom/8/BX/KK0PKLSBCS50IVJIYZKNHT.uasset
  Source/SidheRigel/Minion/Minion.cpp
  Source/SidheRigel/Minion/Minion.h
  Source/SidheRigel/Minion/MinionSpawner.cpp
  Source/SidheRigel/Minion/MinionSpawner.h
  Source/SidheRigel/Minion/RangeMinion.cpp
  Source/SidheRigel/Minion/RangeMinion.h
Labels: feature

#139 [Fix] RangeMinionTargeting
  Content/Minion/BP_RangeMinion.uasset
Labels: :lady_beetle: bug

#140 Develop fairy wing sKill particle
  Content/Heros/FairyWIng/Skill/BP_FairyWingEProjectile.uasset
  Content/Heros/FairyWIng/Skill/BP_FairyWingQCollider.uasset
  Content/Heros/FairyWIng/Skill/BP_FairyWingRCollider.uasset
  Content/Heros/FairyWIng/Skill/BP_FairyWingWCollider.uasset
  Content/Heros/FairyWIng/Skill/P_FairyWingESkill.uasset
  Content/Heros/FairyWIng/Skill/P_FairyWingQSkill.uasset
  Content/Heros/FairyWIng/Skill/P_FairyWingRSkill.uasset
  Content/Heros/FairyWIng/Skill/P_FairyWingWSkill.uasset
Labels: feature

#141 Develop map light intensity decrease
  Content/__ExternalActors__/Maps/TrainingRoom/1/E1/KN27DKHBPQDK3968H3L9TL.uasset
Labels: feature

#142 Develop kerun animation
  Content/Heros/Kerun/Animations/Anim_KerunAttackMontage.uasset
  Content/Heros/Kerun/Animations/Anim_KerunRSkillMontage.uasset
  Content/Heros/Kerun/Animations/Anim_KerunWSkillEnd.uasset
  Content/Heros/Kerun/Animations/Anim_KerunWSkillStart.uasset
  Content/Heros/Kerun/BP_KerunCharacter.uasset
  Source/SidheRigel/Character/Kerun/KerunCharacter.cpp
  Source/SidheRigel/Character/Kerun/KerunCharacter.h
  Source/SidheRigel/Character/Kerun/Skills/KerunR1Skill.cpp
  Source/SidheRigel/Character/Kerun/Skills/KerunWSkill.cpp
  Source/SidheRigel/Character/Kerun/Skills/KerunWSkill.h
Labels: feature

#143 [Fix] When Minion Move, break Attack Anim
  Content/Minion/ABP_Minion.uasset
  Content/Minion/ABP_RangeMinion.uasset
Labels: :lady_beetle: bug

#145 Develop kerun skill particle
  Content/Heros/Kerun/BP_KerunCharacter.uasset
  Content/Heros/Kerun/Skills/P_Kerun_Q_Skill.uasset
  Content/Heros/Kerun/Skills/P_Kerun_RSkill.uasset
  Content/Heros/Kerun/Skills/P_Kerun_WSkill.uasset
  Source/SidheRigel/Character/Kerun/KerunAttackProjectile.cpp
  Source/SidheRigel/Character/Kerun/KerunCharacter.cpp
  Source/SidheRigel/Character/Kerun/KerunCharacter.h
  Source/SidheRigel/Character/Kerun/Skills/KerunR1Skill.cpp
  Source/SidheRigel/Character/Kerun/Skills/KerunWSkill.cpp
Labels: feature

#144 [Fix] When Kerun Use Q Skill, Get Correct Rotation
  Source/SidheRigel/State/UseSkillState.cpp
Labels: :lady_beetle: bug

#146 [Fix] Make Exception to PassiveSkill
  Source/SidheRigel/State/StateMachine.cpp
Labels: :lady_beetle: bug

#148 Develop cc effect
  Content/Heros/Common/BP_SilenceParticle.uasset
  Content/Heros/Common/BP_SlowParticle.uasset
  Content/Heros/Common/BP_StopParticle.uasset
  Content/Heros/Common/BP_StunParticle.uasset
  Content/Heros/Common/M_Slow.uasset
  Content/Heros/Common/P_Slow.uasset
  Content/Heros/Common/P_Stop.uasset
  Content/Heros/Common/P_Stun.uasset
  Content/Heros/Common/WBP_Silence.uasset
  Content/Heros/Common/silence.png
  Content/Heros/Common/silence.uasset
  Content/Maps/Mainmenu.umap
  Source/SidheRigel/Character/Common/SilenceParticle.cpp
  Source/SidheRigel/Character/Common/SilenceParticle.h
  Source/SidheRigel/Character/Common/SlowParticle.cpp
  Source/SidheRigel/Character/Common/SlowParticle.h
  Source/SidheRigel/Character/Common/StopParticle.cpp
  Source/SidheRigel/Character/Common/StopParticle.h
  Source/SidheRigel/Character/Common/StunParticle.cpp
  Source/SidheRigel/Character/Common/StunParticle.h
  Source/SidheRigel/Minion/Minion.cpp
  Source/SidheRigel/Minion/Minion.h
  Source/SidheRigel/SidheRigelCharacter.cpp
  Source/SidheRigel/SidheRigelCharacter.h
  Source/SidheRigel/State/StateMachine.cpp
  Source/SidheRigel/State/StunState.cpp
  Source/SidheRigel/State/StunState.h
Labels: feature

#147 Develop fairy wing skill implement
  Content/Heros/FairyWIng/ABP_FairyWingCharacter.uasset
  Content/Heros/FairyWIng/Animations/Anim_FairyWingAttackMontage.uasset
  Content/Heros/FairyWIng/Animations/Anim_FairyWingESkillMontage.uasset
  Content/Heros/FairyWIng/Animations/Anim_FairyWingQSkillMontage.uasset
  Content/Heros/FairyWIng/Animations/Anim_FairyWingRSkillMontage.uasset
  Content/Heros/FairyWIng/Animations/Anim_FairyWingWSkillMontage.uasset
  Content/Heros/FairyWIng/BP_FairyWingCharacter.uasset
  Content/Heros/FairyWIng/Skill/BP_FairyWingRCollider.uasset
  Content/Heros/FairyWIng/Skill/SM_FairyWingRCollider.uasset
  Source/SidheRigel/Character/FairyWing/FairyWingCharacter.cpp
  Source/SidheRigel/Character/FairyWing/FairyWingCharacter.h
  Source/SidheRigel/Character/FairyWing/Skill/FairyWingESkill.cpp
  Source/SidheRigel/Character/FairyWing/Skill/FairyWingQSkill.cpp
  Source/SidheRigel/Character/FairyWing/Skill/FairyWingRSkill.cpp
  Source/SidheRigel/Character/FairyWing/Skill/FairyWingWSkill.cpp
Labels: feature

#151 Develop talent icon
  Content/Heros/Cold/TalentIcons/Cold_1_1.uasset
  Content/Heros/Cold/TalentIcons/Cold_1_2.uasset
  Content/Heros/Cold/TalentIcons/Cold_1_3.uasset
  Content/Heros/Cold/TalentIcons/Cold_2_1.uasset
  Content/Heros/Cold/TalentIcons/Cold_2_2.uasset
  Content/Heros/Cold/TalentIcons/Cold_2_3.uasset
  Content/Heros/Cold/TalentIcons/Cold_3_1.uasset
  Content/Heros/Cold/TalentIcons/Cold_3_2.uasset
  Content/Heros/Cold/TalentIcons/Cold_3_3.uasset
  Content/Heros/Cold/TalentIcons/Cold_4_1.uasset
  Content/Heros/Cold/TalentIcons/Cold_5_1.uasset
  Content/Heros/Cold/TalentIcons/Cold_5_2.uasset
  Content/Heros/Cold/TalentIcons/Cold_5_3.uasset
  Content/Heros/Cold/TalentIcons/Cold_6_1.uasset
  Content/Heros/Cold/TalentIcons/Cold_6_2.uasset
  Content/Heros/Cold/TalentIcons/Cold_6_3.uasset
  Content/Heros/Cold/TalentIcons/Cold_7_1.uasset
  Content/Heros/Cold/TalentIcons/Cold_7_2.uasset
  Content/Heros/Cold/TalentIcons/Cold_7_3.uasset
  Content/Heros/FairyWIng/TalentIcons/FairyWing_1_1.uasset
  Content/Heros/FairyWIng/TalentIcons/FairyWing_1_2.uasset
  Content/Heros/FairyWIng/TalentIcons/FairyWing_1_3.uasset
  Content/Heros/FairyWIng/TalentIcons/FairyWing_2_1.uasset
  Content/Heros/FairyWIng/TalentIcons/FairyWing_2_2.uasset
  Content/Heros/FairyWIng/TalentIcons/FairyWing_2_3.uasset
  Content/Heros/FairyWIng/TalentIcons/FairyWing_3_1.uasset
  Content/Heros/FairyWIng/TalentIcons/FairyWing_3_2.uasset
  Content/Heros/FairyWIng/TalentIcons/FairyWing_3_3.uasset
  Content/Heros/FairyWIng/TalentIcons/FairyWing_4_1.uasset
  Content/Heros/FairyWIng/TalentIcons/FairyWing_5_1.uasset
  Content/Heros/FairyWIng/TalentIcons/FairyWing_5_2.uasset
  Content/Heros/FairyWIng/TalentIcons/FairyWing_5_3.uasset
  Content/Heros/FairyWIng/TalentIcons/FairyWing_6_1.uasset
  Content/Heros/FairyWIng/TalentIcons/FairyWing_6_2.uasset
  Content/Heros/FairyWIng/TalentIcons/FairyWing_6_3.uasset
  Content/Heros/FairyWIng/TalentIcons/FairyWing_7_1.uasset
  Content/Heros/FairyWIng/TalentIcons/FairyWing_7_2.uasset
  Content/Heros/FairyWIng/TalentIcons/FairyWing_7_3.uasset
  Content/Heros/Kerun/TalentIcons/Kerun_1_1.uasset
  Content/Heros/Kerun/TalentIcons/Kerun_1_2.uasset
  Content/Heros/Kerun/TalentIcons/Kerun_1_3.uasset
  Content/Heros/Kerun/TalentIcons/Kerun_2_1.uasset
  Content/Heros/Kerun/TalentIcons/Kerun_2_2.uasset
  Content/Heros/Kerun/TalentIcons/Kerun_2_3.uasset
  Content/Heros/Kerun/TalentIcons/Kerun_3_1.uasset
  Content/Heros/Kerun/TalentIcons/Kerun_3_2.uasset
  Content/Heros/Kerun/TalentIcons/Kerun_3_3.uasset
  Content/Heros/Kerun/TalentIcons/Kerun_4_1.uasset
  Content/Heros/Kerun/TalentIcons/Kerun_5_1.uasset
  Content/Heros/Kerun/TalentIcons/Kerun_5_2.uasset
  Content/Heros/Kerun/TalentIcons/Kerun_5_3.uasset
  Content/Heros/Kerun/TalentIcons/Kerun_6_1.uasset
  Content/Heros/Kerun/TalentIcons/Kerun_6_2.uasset
  Content/Heros/Kerun/TalentIcons/Kerun_6_3.uasset
  Content/Heros/Kerun/TalentIcons/Kerun_7_1.uasset
  Content/Heros/Kerun/TalentIcons/Kerun_7_2.uasset
  Content/Heros/Kerun/TalentIcons/Kerun_7_3.uasset
Labels: feature

#153 Develop server problem
  Config/DefaultEngine.ini
  Content/Maps/Lobby.umap
  Content/UIBlueprints/WBP_LobbyMenu.uasset
  Content/UIBlueprints/WBP_Mainmenu.uasset
  Content/__ExternalActors__/Maps/TrainingRoom/2/N3/I923VRLHN6VQI6XDVX0SAH.uasset
  Content/__ExternalActors__/Maps/TrainingRoom/C/X6/439DNIF9DSZY6L5A28D5BV.uasset
  Source/SidheRigel.Target.cs
  Source/SidheRigel/Lobby/LobbyGameMode.cpp
  Source/SidheRigel/Lobby/LobbyGameMode.h
  Source/SidheRigel/Lobby/LobbyMenu.cpp
  Source/SidheRigel/Lobby/LobbyMenu.h
  Source/SidheRigel/Lobby/LobbyPlayerController.cpp
  Source/SidheRigel/Lobby/LobbyPlayerController.h
  Source/SidheRigel/MainMenu/MainMenu.cpp
  Source/SidheRigel/SidheRigel.Build.cs
  Source/SidheRigel/SidheRigelCharacter.cpp
  Source/SidheRigel/SidheRigelGameInstance.cpp
  Source/SidheRigel/SidheRigelGameInstance.h
  Source/SidheRigel/SidheRigelGameMode.cpp
Labels: :lady_beetle: bug

#154 [Fix] Can Enter Single
  Source/SidheRigel/Lobby/LobbyGameMode.cpp
  Source/SidheRigel/Lobby/LobbyGameMode.h
  Source/SidheRigel/Lobby/LobbyPlayerController.cpp
Labels: :lady_beetle: bug

#155 [Update] Change TalentUI to Image
  Content/UIBlueprints/InGameUI/WBP_TalentItem.uasset
  Source/SidheRigel/Character/Cold/ColdCharacter.cpp
  Source/SidheRigel/Character/FairyWing/FairyWingCharacter.cpp
  Source/SidheRigel/Character/Kerun/KerunCharacter.cpp
  Source/SidheRigel/UI/TalentItem.cpp
Labels: feature

#156 Develop server problem
  Config/DefaultEngine.ini
  Content/__ExternalActors__/Maps/TrainingRoom/2/4K/JHN8LY0ZM6ZAADJJHN4YKL.uasset
  Content/__ExternalActors__/Maps/TrainingRoom/2/9E/ZI5P8YZ5Q13UK9K9JO9L9X.uasset
  Content/__ExternalActors__/Maps/TrainingRoom/2/N3/I923VRLHN6VQI6XDVX0SAH.uasset
  Content/__ExternalActors__/Maps/TrainingRoom/4/6R/GUY5SFVGTK03WDGEIJ50WW.uasset
  Content/__ExternalActors__/Maps/TrainingRoom/4/P4/NY1I5GSIDWDMI4KX9UHZWN.uasset
  Content/__ExternalActors__/Maps/TrainingRoom/8/PB/JLKRW5KBD5U51YM2R8SO2A.uasset
  Content/__ExternalActors__/Maps/TrainingRoom/C/X6/439DNIF9DSZY6L5A28D5BV.uasset
  Content/__ExternalActors__/Maps/TrainingRoom/D/8W/V712QLIWRXQVWX0V9BLD8X.uasset
  Content/__ExternalActors__/Maps/TrainingRoom/F/0O/KIDSXGRJXC47I54T92XQVB.uasset
  Source/SidheRigel/Lobby/LobbyGameMode.cpp
  Source/SidheRigel/Lobby/LobbyMenu.cpp
  Source/SidheRigel/SidheRigelCharacter.cpp
  Source/SidheRigel/SidheRigelCharacter.h
  Source/SidheRigel/SidheRigelGameInstance.h
  Source/SidheRigel/SidheRigelGameMode.cpp
  Source/SidheRigel/SidheRigelGameMode.h
  Source/SidheRigel/SidheRigelPlayerController.cpp
  Source/SidheRigel/SidheRigelPlayerController.h
  Source/SidheRigel/State/IdleState.cpp
  Source/SidheRigel/State/MoveState.cpp
  Source/SidheRigel/State/MoveToAttackState.cpp
Labels: feature

#158 Develop server problem
  Content/Minion/BP_MinionSpawner.uasset
  Content/__ExternalActors__/Maps/TrainingRoom/2/9E/ZI5P8YZ5Q13UK9K9JO9L9X.uasset
  Source/SidheRigel/Minion/Minion.cpp
  Source/SidheRigel/Minion/Minion.h
  Source/SidheRigel/Minion/MinionSpawner.cpp
  Source/SidheRigel/Minion/MinionSpawner.h
  Source/SidheRigel/Minion/RangeMinion.cpp
  Source/SidheRigel/Minion/RangeMinion.h
  Source/SidheRigel/SidheRigelCharacter.cpp
  Source/SidheRigel/SidheRigelPlayerController.cpp
  Source/SidheRigel/SidheRigelPlayerController.h
  Source/SidheRigel/State/AttackState.cpp
  Source/SidheRigel/State/MoveToAttackState.cpp
Labels: :lady_beetle: bug

#159 Develop bulidings
  Content/Nexus/BP_DestroyNexusParticle.uasset
  Content/Nexus/BP_NexusAttackProjectile.uasset
  Content/Nexus/SW_DestroyNexus.uasset
  Content/Nexus/SW_NexusAttack.uasset
  Content/Tower/BP_DestroyTowerParticle.uasset
  Content/Tower/BP_TowerAttackProjectile.uasset
  Content/Tower/SW_DestroyTower.uasset
  Content/Tower/SW_TowerAttack.uasset
  Source/SidheRigel/Nexus/Nexus.cpp
  Source/SidheRigel/Nexus/Nexus.h
  Source/SidheRigel/Nexus/NexusDestroyParticle.cpp
  Source/SidheRigel/Nexus/NexusDestroyParticle.h
  Source/SidheRigel/Tower/Tower.cpp
  Source/SidheRigel/Tower/Tower.h
  Source/SidheRigel/Tower/TowerDestroyParticle.cpp
  Source/SidheRigel/Tower/TowerDestroyParticle.h
Labels: :lady_beetle: bug

#160 Develop server problem
  Source/SidheRigel/Lobby/LobbyPlayerController.cpp
  Source/SidheRigel/Minion/Minion.cpp
  Source/SidheRigel/Minion/MinionSpawner.cpp
  Source/SidheRigel/SidheRigelCharacter.cpp
  Source/SidheRigel/SidheRigelPlayerController.cpp
Labels: :lady_beetle: bug
